import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import SubNavBar from '@/components/SubNavBar'
import EventCard from '@/components/EventCard'
import axios from 'axios'
import { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import TeamCard from '@/components/TeamCard'
import NotificationCenter from '@/components/NotficationCenter'
// import NotificationCenter from '@/components/notficationCenter'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [events, setEvents] = useState([])
  const [loading, setLoading] = useState(true)
  const { user, login } = useAuth()

  useEffect(() => {
    console.log(user);
    setLoading(true)
    axios.get(`http://localhost:8080/createEvent/${user.uid}`).then((res) => {
      setEvents(res.data)
      setLoading(false)
    }).catch((err) => {
       setLoading(false)
       alert("Something went wrong")
    })
  }, [])
  return (
    <>
      <Head>
        <title>GatherUp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavBar/>
      <SubNavBar/>

      {
        events.length === 0 ?
        <div style={{display: 'flex',flexDirection: 'column', justifyContent: 'center', alignItems: 'center', width: '100vw', marginTop: 150}}>
          <h1>No Events Created</h1>
          <p style={{marginTop: 20}}>Tap on the + icon to create an event</p>
        </div> : 
        events.map((event) => (
          <EventCard title={event.title} description={event.description} startDate={event.startDate} endDate={event.endDate} venue={event.venue}/>
        ))
      }
    </>
  )
}
