import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import SubNavBar from '@/components/SubNavBar'
import EventCard from '@/components/EventCard'
import TeamCard from '@/components/TeamCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GatherUp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavBar/>
      <SubNavBar/>

      
      <EventCard/>
      <TeamCard name="Vishal Chinnasamy" email="vishalchinns1650@gmail.com" eventRole="Event Owner"/>

    </>
  )
}
